name: Release
on:
  # manual trigger
  workflow_dispatch:

jobs:
  bump_version:
    name: Bump Version
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.github_tag_action.outputs.new_tag }}
      changelog: ${{ steps.github_tag_action.outputs.changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Bump version and push tag
        id: github_tag_action
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: .*

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: bump_version
    if: ${{ needs.bump_version.outputs.new_tag != null }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Build the app
        run: yarn run build

      - name: Export SSG
        run: yarn run export

      - name: Deploy to IPFS
        uses: web3-storage/add-to-web3@v2
        id: web3
        with:
          path_to_add: out
          web3_token: ${{ secrets.WEB3_STORAGE_TOKEN}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update DNS with new IPFS hash testnet
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          RECORD_DOMAIN: "kongkowitpku.xyz"
          RECORD_NAME: "_dnslink"
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: npx dnslink-cloudflare --record _dnslink --domain kongkowitpku.xyz --link /ipfs/${{ steps.web3.outputs.cid }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.bump_version.outputs.new_tag }}
          release_name: Release ${{ needs.bump_version.outputs.new_tag }}
          body: |
            IPFS hash of the deployment:
            - **CID Hex Digest**: `${{ steps.web3.outputs.cid }}`
            The latest release is always accessible via an alias to the Cloudflare IPFS gateway at [kongkowitpku.xyz](https://kongkowitpku.xyz).
            You can also access This Page from any IPFS gateway.
            **You should always use an IPFS gateway that enforces origin separation**, or the alias to the latest release at [kongkowitpku.xyz](https://kongkowitpku.xyz).
            IPFS gateways:
            - https://${{ steps.web3.outputs.cid }}.ipfs.w3s.link
            - https://${{ steps.web3.outputs.cid }}.ipfs.dweb.link
            - https://${{ steps.web3.outputs.cid }}.ipfs.cf-ipfs.com
